config/routes.rb
Hamburgbrewingco::Application.routes.draw do
  devise_for :users

  resources :locations

  root :to => 'pages#home'
  get 'brewery' => 'pages#brewery'
  get 'locations' => 'locations#index'
  get 'events' => 'pages#events'
  get 'farm' => 'pages#farm'
  get 'beers' => 'pages#beers'
  get 'menu' => 'pages#menu'
  get 'age' => 'pages#age'
  
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :name, :vender, :phone, :website, :url
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  
  # GET /locations
  # GET /locations.json
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_path, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to locations_path, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
<div class="container">
<hr/>
	<div class="fb-like sidebar-box" data-href="https://www.facebook.com/pages/Hamburg-Brewing-Company/496661553713375" data-send="true" data-width="100" data-show-faces="true"></div>
	<hr/>
	<ul>
		<li><a href="/beers">Beers</a></li>
		<li><a href="/locations">Beer Finder</a></li>
		<li><a href="/brewery">Brewery</a></li>
		<li><a href="/events">Events</a></li>
		<% if user_signed_in? %>
		<li><%= link_to "Admin Logout", destroy_user_session_path, method: :delete %></li>
		<% else %>
		<li><%= link_to "Admin Login", new_user_session_path %></li>		
		<% end %>
	</ul>
	<hr/>
	<div class="row-fluid">
		<div class="span12">
			<div class="span4">
				<p class="muted pull-left"><small>Designed by <a href="http://www.vergetone.com/" target="blank">Vergetone</a></small></p>
			</div>
			<div class="span6 pull-right">
				<p class="muted pull-right"><small>© 2013 Hamburg Brewing Company</small></p>
			</div>
		</div>
	</div>

	</div>
</div>

app/views/layouts/_header.html.erb
<script>
$(document).scroll(function () {
    var value = $(this).scrollTop();
    if ( value > 120 ) {
        $('.topMenu').fadeIn();
    } else {
        $('.topMenu').fadeOut();
    }

});
</script>

<div class="topMenu container">
  <div class="container">
<span class="logo"><a href="/"><img src="/HBCEmblem.png" style="width: 7%"/></a></span>  
<ul class="pull-right">
  <b><li><a href="/beers">BEERS</a></li>
  <li>|</li>
  <li><a href="/locations">BEER FINDER</a></li>
  <li>|</li>
  <li><a href="/brewery">BREWERY</a></li>
  <li>|</li>
  <li><a href="/events">EVENTS</a></li></b>
</ul>
</div>
</div>

<div class="mainMenu container center">
  <b><ul>
    <li><a href="/beers">BEERS</a></li>
    <li>|</li>
    <li><a href="/locations">BEER FINDER</a></li>
    <li3>|</li3>
    <li2><span><a href="/"><img src="/HeaderLogo.png" style="width: 25%"/></a></span></li2>
    <li4>|</li4>
    <li><a href="/brewery">BREWERY</a></li>
    <li>|</li>
    <li><a href="/events">EVENTS</a></li>
  </ul></b>
</div>

app/views/layouts/_sidebar.html.erb
<div style="width:195px; text-align:center;" class="sidebar-box" ><p class="lead">HBC Events</p><iframe  src="http://www.eventbrite.com/calendar-widget?eid=7147820323" frameborder="0" height="383" width="195" marginheight="0" marginwidth="0" scrolling="no" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:10px; padding:5px 0 5px; margin:2px; width:195px; text-align:center;" ></div></div>

<a class="twitter-timeline" href="https://twitter.com/HamburgBrewing" data-widget-id="355482650628222976">Tweets by @HamburgBrewing</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hamburg Brewing Company</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-precomposed.png">
    <!--Facebook-->
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!--Facebook-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    
  <div class="container">
    <div class="row">
        <div class="span9">
         <% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %> 
        <%= yield %>
        </div>
        <div class="span2">
          <div class="sidebar">
          <%= render 'layouts/sidebar' %>
          </div>
        </div>
    </div>
  </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/locations/_edit_form.html.erb
<%= simple_form_for(@location, html: {class: "form-horizontal"}) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
  <%= f.input :vender, :as => :select, 
                 :label => "Vender", :include_blank => false,
                 :collection => ["Bar", "Store"] %>
  </div>
  <div class="field">
    <%= f.label "Website URL" %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label "Website Display Name" %><br />
    <%= f.text_field :website %>
  </div>
  <br>
  <button type="submit" class="btn btn-primary">Save</button>
<% end %>

app/views/locations/_form.html.erb
<%= simple_form_for(@location, html: {class: "form-horizontal"}) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
  <%= f.input :vender, :as => :select, 
                 :label => "Vender", :include_blank => false,
                 :collection => ["Bar", "Store"] %>
  </div>
  <div class="field">
    <%= f.label "Website URL" %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label "Website Display Name" %><br />
    <%= f.text_field :website %>
  </div>
  <br>
  <button type="submit" class="btn btn-primary">Add Location</button>
<% end %>

app/views/locations/edit.html.erb
<div class="form-box">
<h1>Edit location</h1>

<%= render 'edit_form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>
</div>

app/views/locations/index.html.erb
<div class="location-box">
<h1>Brew Near You</h1>

<p class="lead">Here are the current locations where you can find the Hamburg Brewing Company beers.
Check back
frequently, more locations are being added! 
</p>
<%= form_tag locations_path, :method => :get do %>
  <span class="beersearch">
    <%= text_field_tag :search, params[:search], :placeholder => 'Enter your location...', :class => "beersearch", :style => "height:36px; width:260px;font-size:20pt;" %>
  </span>
    <button type="submit" class="btn btn-primary btn-large">Find me some Hamburg!</button>
  
<% end %>

<html>
  <head>
    <style>
    body { font-family: Helvetica; }
    .map-content h3 { margin: 0; padding: 5px 0 0 0; }
    </style>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true"></script>
    <script>
  // Set the Map variable
        var map;
        function initialize() { 
            var myOptions = {
            zoom: 9,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
                    
        var infoWindow = new google.maps.InfoWindow;
        map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);
        // Set the center of the map


        <% if params[:search].present? %>
        <% @locations.each do |location| %>
        var pos = new google.maps.LatLng(<%= location.latitude %>, <%= location.longitude %>);
        map.setCenter(pos);
        <% end %>
        <% else %>
        var pos = new google.maps.LatLng(42.715893, -78.829477);
        map.setCenter(pos);
        <% end %>

        function infoCallback(infowindow, marker) { 
            return function() {
            infowindow.open(map, marker);
        };
   }    
        var image = '/HBCMarker.png';

        var all = [
        <% @locations.each do |location| %>
          ["<%= location.name %>", "<%= location.address %>", "<%= location.website %>", "<%= location.phone %>", "<%= location.latitude %>", "<%= location.longitude %>"],
        <% end %>
        ];

   function setMarkers(map, all) {  
    for (var i in all) {                    
            var name  = all[i][0];
            var address = all[i][1];
            var city  = all[i][2];
            var state  = all[i][3];
            var zip   = all[i][0];
            var lat   = all[i][4];
            var lng   = all[i][5];
            var latlngset;
            latlngset = new google.maps.LatLng(lat, lng);
            var marker = new google.maps.Marker({  
              map: map,  title: name,  position: latlngset, icon: image  
            });
            var content = '<div class="map-content"><h3>' + name + '</h3>' + address + '<br />' + city + '<br /><a href="http://maps.google.com/?daddr=' + address + '" target="_blank">Get Directions</a></div>';         
            var infowindow = new google.maps.InfoWindow();
              infowindow.setContent(content);
              google.maps.event.addListener(
                marker, 
                'click', 
                infoCallback(infowindow, marker)
              );
          }
        }     
        // Set all markers in the all variable
        setMarkers(map, all);
      };
      // Initializes the Google Map
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>
  <% if @locations.empty? %>
  <span class="center">No Hamburg beers near that location (yet!).<a href="/locations"> Search again?</a></span>
  <% else %>
  <a href="/locations">Show all</a>
  <% end %>
  <body>
    <div id="map_canvas" style="height: 400px; width: 800;"></div>
  </body>
</html>

<table class="table table-striped">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Address</th>
    <th>Type</th>
    <th>Website</th>
    <th></th>
  </tr>
<% @locations.each do |location| %>
  <tr>
    <td><img src="/HBCEmblemSmall.png" style="width: 60%;"/></td>
    <td><%= location.name %></td>
    <td><%= location.address %></td>
    <td><%= location.vender %></td>
    <td><a href="<%= location.url %>" target="blank"><%= location.website %></a> </td>
    <% if user_signed_in? %>
    <td><%= link_to raw('<i class="icon-edit"></i>'), edit_location_path(location), :class => 'btn' %></td>
    <td><%= link_to raw('<i class="icon-trash"></i>'), location, method: :delete, :class => 'btn', data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in? %>
<%= link_to 'New Location', new_location_path, :class => 'btn' %>
<% end %>
</div>

app/views/locations/new.html.erb
<div class="form-box">
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>
</div>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @location.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<head>
<script
src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
</script>

<script>
var myCenter=new google.maps.LatLng(<%= @location.latitude %>,<%= @location.longitude %>);

function initialize()
{
var mapProp = {
  center:myCenter,
  zoom:5,
  mapTypeId:google.maps.MapTypeId.ROADMAP
  };

var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

var marker=new google.maps.Marker({
  position:myCenter,
  });

marker.setMap(map);

var infowindow = new google.maps.InfoWindow({
  content:"Hello World!"
  });

google.maps.event.addListener(marker, 'click', function() {
  infowindow.open(map,marker);
  });
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
</head>

<body>
<div id="googleMap" style="width:500px;height:380px;"></div>
</body>

<h1>Nearby Locations</h1>
<ul>
<% for location in @location.nearbys(10) %>
	<li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<div class="about-box">
<h1>About Us</h1>
<div id="myCarousel" class="carousel slide">
	<div class="carousel-inner">
	  <div class="item active">
	    <img src="/Business_card_5.jpg" alt="">
	    <div class="carousel-caption">
	      <h4>First Thumbnail label</h4>
	      <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	    </div>
	  </div>
	  <div class="item">
	    <img src="/1002428_567225823323614_1239472127_n.jpg" alt="">
	    <div class="carousel-caption">
	      <h4>Second Thumbnail label</h4>
	      <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	    </div>
	  </div>
	  <div class="item">
	    <img src="/1002972_567225893323607_1897345853_n.jpg" alt="">
	    <div class="carousel-caption">
	      <h4>Third Thumbnail label</h4>
	      <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	    </div>
	  </div>
	  <div class="item">
	    <img src="/1013914_567225849990278_1840241144_n.jpg" alt="">
	    <div class="carousel-caption">
	      <h4>Third Thumbnail label</h4>
	      <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	    </div>
	  </div>
	  <div class="item">
	    <img src="/1014346_567227583323438_4178025_n.jpg" alt="">
	    <div class="carousel-caption">
	      <h4>Third Thumbnail label</h4>
	      <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	    </div>
	  </div>
	  <div class="item">
	    <img src="/bar.JPG" alt="">
	    <div class="carousel-caption">
	      <h4>Third Thumbnail label</h4>
	      <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	    </div>
	  </div>
	</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
	</div>
	
	<h1>Hamburg Brewing Company</h1>
	<p class="lead">
		The Hamburg Brewing Company is dedicated to crafting great beers. We are determined to further enhance the history and ever-growing beer culture found in the Western New York area by letting our fresh, high quality products speak for themselves.
	</p>
</div>
</html>

app/views/pages/beers.html.erb
<div class="location-box">
	<h1>Hamburg Beers</h1>
<div>
	<p>
		The Hamburg Brewing Company is dedicated to crafting great beers. We are determined to further enhance the history and ever-growing beer culture found in the Western New York area by letting our fresh, high quality products speak for themselves.</p>
</div>
<br>
<div>
	<h2><img src="/HBCEmblem.png" style="width: 5%;"/> “White Corner” Wheat  5.3%</h2>
	<p>
		Brewed with a heavy helping of American grown malted wheat, two-row malted barley, and a hint of Meridian and Perle hops. White Corner  Wheat is a refreshingly delicate beer meant to quench your thirst. The name derives from our hometown of Hamburg, which was originally named White’s Corner in the 1800’s. This is Hamburg’s beer.
	</p>
	<h2><img src="/HBCEmblem.png" style="width: 5%;"/> India Pale Ale 6.0%</h2>
	<p>
		This take on the iconic IPA style includes four different types of malted barley creating a unique orange hue. Hops added throughout the brewing process add floral and piney aromas that mingle well with the distinct malty character.
	</p>
	<h2><img src="/HBCEmblem.png" style="width: 5%;"/> “No Lux” 7.0%</h2>
	<p>
		Black as night, “No Lux” has been packed with a wide variety of specialty malts.  Deeply roasted malt, caramel malt, rye, and pale malt are all used to give backbone to the Cascadian, Centennial, and Chinook hops added en masse.  At first sip a low to medium body is noticed followed by a robust roasted character with a hop dominated finish.
	</p>
	<h2><img src="/HBCEmblem.png" style="width: 5%;"/> Oktoberfest  5.7%</h2>
	<p>
		Oktoberfest is the great fall seasonal style.  This lager is brewed primarily with Vienna style malts to bring about big malty flavor. The malty/sweetness starts first then fades away to nice hop bitterness.
	</p>
	<h2><img src="/HBCEmblem.png" style="width: 5%;"/> “Small Town“ Saison 5.2%</h2>
	<p>
		Saison is the traditional Belgian farmhouse beer, first brewed on farm estates primarily for the workers tending to the fields.  This Saison consists of pilsner malt and white wheat malt for a dry, refreshingly lighter beer. The Belgian yeast enjoys a warm fermentation to impart a fruity/spicy undertone so as to give this beer its distinct characteristics.
	</p>
</div>
</div>

app/views/pages/brewery.html.erb
<!DOCTYPE html>
<html>
<div class="about-box">
<h1>About Us</h1>
<div id="myCarousel" class="carousel slide">
	<div class="carousel-inner">
	  <div class="item active">
	    <img src="/Business_card_5.jpg" alt="">
	    <div class="carousel-caption">
	      <h4></h4>
	      <p></p>
	    </div>
	  </div>
	  <div class="item">
	    <img src="/taps.JPG" alt="">
	    <div class="carousel-caption">
	      <h4></h4>
	      <p></p>
	    </div>
	  </div>
	  <div class="item">
	    <img src="/barnew.JPG" alt="">
	    <div class="carousel-caption">
	      <h4></h4>
	      <p></p>
	    </div>
	  </div>
	</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
	</div>
	<div class="span5">
	<h1>Hamburg Brewing Company</h1>
	<p class="lead">
		The Hamburg Brewing Company is dedicated to crafting great beers. We are determined to further enhance the history and ever-growing beer culture found in the Western New York area by letting our fresh, high quality products speak for themselves.
		<br>
		<br>
		We are not currently filling kegs for home use, but will be soon. Stay tuned…
	</p>
	<p class="lead">	
		<a href="mailto:info@hamburgbrewing.com?subject=Feedback">Email us</a> with any questions
	</p>
	</div>
	<div class="span3">
	<p class="lead"><b>Taproom Hours</b></p>
	<ul class="lead">
		<li><b>Wed:</b> 4-10pm</li>
		<li><b>Thurs:</b> 4-10pm</li>
		<li><b>Fri:</b> 4-10pm</li>
		<li><b>Sat:</b> 12-10pm</li>
		<li><b>Sun:</b> 12-6pm</li>
	</ul>
	<p class="lead">
		<a href="/menu">View Menu</a>
	</p>
	<p class="lead">
		6553 Boston State Rd<br>
		Hamburg, NY 14075
	</p>
</div>
	
</div>
</html>

app/views/pages/events.html.erb
<head>
<script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type='text/javascript' src="http://evbdn.eventbrite.com/s3-s3/static/js/platform/Eventbrite.jquery.js"></script>
<script type='text/javascript'>
$(document).ready(function(){
  Eventbrite({'app_key': "UYRU72L7OQUHWLHV7J"}, function(eb){
    eb.organizer_list_events( {'id': 4212334371, 'statuses': "live,started"}, function( response ){
      var event_list_html = eb.utils.eventList( response, eb.utils.eventListRow );
          $("#event-list").html(event_list_html);
    });
  });
});
</script>
<style>
      .eb_event_list_item{
        padding-top: 20px;
        padding-bottom: 20px;
      }
      .eb_event_list_title{
        display:block;
        padding-left: 30px;
        width: 400px;
        overflow: hidden;
        font-size: larger;
      }
      .eb_event_list_date{
        position: absolute;
        left: 30px;
      }
      .eb_event_list_time{
        position: absolute;
        left: 155px;
      }
      .eb_event_list_location{
        position: absolute;
        left: 230px;
      }
      .eb_event_list_description{
        position: absolute;
        left: 230px;
      }
  </style>
</head>
<body>
  <div class="about-box span9"><iframe src="http://hamburgbrewco.eventbrite.com/" width="100%" height="1000" frameborder="0"></iframe></div>
</body>

app/views/pages/farm.html.erb
<!DOCTYPE html>
<html>
<h1>The Farm</h1>
<img src="/farm1.JPG"/>

</html>

app/views/pages/home.html.erb
<div class="about-box">
<div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
          <div class="item active">
            <img src="/taps.JPG" alt="">
            <div class="carousel-caption">
              <h4></h4>
              <p></p>
            </div>
          </div>
          <div class="item">
            <img src="/barnew.JPG" alt="">
            <div class="carousel-caption">
              <h4></h4>
              <p></p>
            </div>
          </div>
          <div class="item">
            <img src="/hops.JPG" alt="">
            <div class="carousel-caption">
              <h4></h4>
              <p></p>
            </div>
          </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
      </div>
    <div class="row-fluid">
        <div class="span6">
          <h2>Beer Finder</h2>
          <p class="lead">Looking for our beer? Click here to find out where it is.</p>
          <p><a class="btn" href="/locations">Find HBC &raquo;</a></p>
        </div>
        <div class="span6">
          <h2>Events</h2>
          <p class="lead">Click here for upcoming events!</p>
          <p><a class="btn" href="/events">Meet up &raquo;</a></p>
       </div>
   </div>
</div>

app/views/pages/menu.html.erb
<div class="location-box">

	<p class="center">
		<img src="/hbcmenu.png"/>
	</p>

</div>